[package]
name = "native"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "native_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.12", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha.18", features = ["shell-open", "shell-command", "fs-all", "path-all", "process-command-api", "dialog-all", "notification-all", "global-shortcut-all", "os-all", "window-all", "tray-all", "menu-all", "clipboard-all", "protocol-all", "http-all", "websocket-all", "updater-all", "autostart-all", "single-instance-all", "window-state-all", "window-effects-all", "window-shadows-all", "window-decorations-all", "window-transparent-all", "window-vibrancy-all", "window-blur-all", "window-titlebar-style-all", "window-titlebar-buttons-all", "window-titlebar-icon-all", "window-titlebar-text-all", "window-titlebar-menu-all", "window-titlebar-minimize-all", "window-titlebar-maximize-all", "window-titlebar-close-all", "window-titlebar-fullscreen-all", "window-titlebar-hide-all", "window-titlebar-show-all", "window-titlebar-toggle-all", "window-titlebar-is-visible-all", "window-titlebar-is-minimized-all", "window-titlebar-is-maximized-all", "window-titlebar-is-fullscreen-all", "window-titlebar-is-hidden-all", "window-titlebar-is-shown-all", "window-titlebar-is-toggled-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
uuid = { version = "1.7", features = ["v4", "serde"] }
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

